apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  labels:
    app: app-backend
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-backend
      
  template:
    metadata:
      labels:
        app: app-backend
        tier: app-backend
    spec:
      containers:
        - name: app-backend
          image: mauikem/app-backend:tagversion
          imagePullPolicy: Always
          ports:
          - containerPort: 4000
            name: app-backend


---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
  labels:
    app: app-backend
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: app-backend
    tier: app-backend
  type: LoadBalancer